#!/usr/bin/env python3

import csv

def get_source(file_location):
    entries = []
    temp = ""
    with open(file_location) as csv_file:
        
        lines = list(csv.reader(csv_file))
        for line in lines:
            temp = line[15] + "," + line[16] + "," + line[19] + " " + line[20] + " " + line[21] + ",," + line[17] + "," + line[1] + " " + line[2] + "," + line[0] + "\n"
            entries.append(temp)
            print(temp)

    return entries


# Appends changes in state for each user to the log file
def append_csv():
    target_location = "/home/localadmin/Documents/Bunbury student group.csv"
    source_location = "/home/localadmin/Documents/PTO Extract.csv"
    
    append_target = get_source(source_location)

    with open(target_location, "a") as csv_file:
        for student in append_target:
            csv_file.write(student)


append_csv()
